POST http://localhost:5000/admin/products


{
    "name": "Hamburger Classico",
    "category": "burger",
    "basePrice": 5,           
    "sizes": [
        {"label": "small", "price": 5, "meatWeight": 100},
        {"label": "medium", "price": 7, "meatWeight": 180},
        {"label": "large", "price": 9.5, "meatWeight": 360}
    ],
    "ingredients": [
        {"name": "Hamburger di manzo"},
        {"name": "Pomodoro"},
        {"name": "Insalata"},
        {"name": "Ketchup"},
        {"name": "Maionese"}
    ],
    "extras": [],
    "imageUrl": "Image not available for now",          
    "available": true,
    "description": "Classic Hamburger: perfect if you don't want an extravagant sandwich"   
}

#####
POST http://localhost:5000/orders
Content-Type: application/json

{
  "_id": { "$oid": "70a1c9f0e1a4c12f9d3a9001" },
  "user": { "$oid": "65b8f2c9e1a4c12f9d3a0001" },
  "items": [
    {
      "product": { "$oid": "696e5c40ee1cede16b3b84d4" },
      "name": "Hamburger Classico (medium)",
      "price": 7,
      "quantity": 2,
      "removedIngredients": ["Pomodoro", "Maionese"],
      "extras": [
        {
          "name": "Extra formaggio",
          "price": 0.50
        }
      ]
    }
  ],
  "status": "pending",
  "subtotal": 16.00,
  "total": 16.00,
  "paymentMethod": "card",
  "paymentStatus": "unpaid",
  "orderType": "take_away",
  "notes": "Hamburger ben cotto",
  "createdAt": { "$date": "2026-01-20T12:00:00.000Z" },
  "updatedAt": { "$date": "2026-01-20T12:00:00.000Z" },
  "__v": 0
}


