GET http://localhost:5000/users

####

GET http://localhost:5000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NmUwMjU5OTJiODQzODc2ZWE3Mzk0OCIsImlhdCI6MTc2ODgxODg5MiwiZXhwIjoxNzY4ODIyNDkyfQ.nk5T54-wqsLnhRT9oNwNDyMHX8OFKs77oBVACFzA1-0
####


POST  http://localhost:5000/auth/register 
Content-Type: application/json

{
    "firstName": "Francesco",
    "lastName":"Totti",
    "email": "vaiuomo@gmail.com",
    "password": "perfavore",
    "phoneNumber":23563,
    "address":{
        "number": 45,
        "street": "C.da Frontuccia "
    }
}


####

POST  http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "vaiuomo@gmail.com",
    "password": "perfavore"
}

####

POST  http://localhost:5000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NmUwMjU5OTJiODQzODc2ZWE3Mzk0OCIsImlhdCI6MTc2ODgxODg5MiwiZXhwIjoxNzY4ODIyNDkyfQ.nk5T54-wqsLnhRT9oNwNDyMHX8OFKs77oBVACFzA1-0

####

PATCH http://localhost:5000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NmUwMjU5OTJiODQzODc2ZWE3Mzk0OCIsImlhdCI6MTc2ODgxODg5MiwiZXhwIjoxNzY4ODIyNDkyfQ.nk5T54-wqsLnhRT9oNwNDyMHX8OFKs77oBVACFzA1-0

{
    "phoneNumber": 12345678,
    "lastName": "Gabbani"
}