GET http://localhost:5000/users

####

POST  http://localhost:5000/auth/register 
Content-Type: application/json

{
    "firstName": "Marco",
    "lastName":"Maariani",
    "email": "omosesfs@gmail.com",
    "password": "acabbdkash",
    "phoneNumber":23563,
    "address":{
        "number": 45,
        "street": "C.da Frontuccia "
    }
}


####

POST  http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "omosesfs@gmail.com",
    "password": "acabbdkash"
}